/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Avu9QsJH4LL
 */
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"

export function SEOCompactKPIsCard() {
  return (
    <Card className="mx-auto max-w-3xl">
      <CardHeader className="pb-0">
        <CardTitle>KPIs</CardTitle>
        <CardDescription>Key Performance Indicators</CardDescription>
      </CardHeader>
      <CardContent className="flex items-center gap-4">
        <div className="flex flex-col items-center gap-1 text-center">
          <div className="font-semibold text-2xl">12.5K</div>
          <Progress className="w-20 h-2 rounded-full" variant="gradient">
            25
          </Progress>
          <div className="text-sm">Search Volume</div>
        </div>
        <div className="flex flex-col items-center gap-1 text-center">
          <div className="font-semibold text-2xl">345</div>
          <Progress className="w-20 h-2 rounded-full" variant="gradient">
            75
          </Progress>
          <div className="text-sm">Clicks</div>
        </div>
        <div className="flex flex-col items-center gap-1 text-center">
          <div className="font-semibold text-2xl">89%</div>
          <Progress className="w-20 h-2 rounded-full" variant="gradient">
            50
          </Progress>
          <div className="text-sm">CTR</div>
        </div>
        <div className="flex flex-col items-center gap-1 text-center">
          <div className="font-semibold text-2xl">4.2</div>
          <Progress className="w-20 h-2 rounded-full" variant="gradient">
            10
          </Progress>
          <div className="text-sm">Bounce Rate</div>
        </div>
      </CardContent>
    </Card>
  )
}
