/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/AWZcMqviHFB
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"
import { TableCell, TableRow, TableBody, Table } from "@/components/ui/table"

export function SEODashboardPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex items-center h-14 px-4 border-b gap-4 lg:h-20 bg-gray-100/40 dark:bg-gray-800/40">
        <Button className="rounded-lg md:hidden" variant="icon">
          <MenuIcon className="h-6 w-6" />
          <span className="sr-only">Toggle sidebar</span>
        </Button>
        <h1 className="font-semibold text-lg lg:text-2xl">SEO</h1>
        <form className="ml-auto flex-1 md:mr-2 lg:mr-4">
          <Input className="w-full md:w-[250px] lg:w-[300px]" placeholder="Search..." type="search" />
        </form>
        <Button className="rounded-full" size="icon" variant="outline">
          <PlusIcon className="w-4 h-4" />
          <span className="sr-only">New item</span>
        </Button>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800"
              size="icon"
              variant="ghost"
            >
              <img
                alt="Avatar"
                className="rounded-full"
                height="32"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "32/32",
                  objectFit: "cover",
                }}
                width="32"
              />
              <span className="sr-only">Toggle user menu</span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>My Account</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Settings</DropdownMenuItem>
            <DropdownMenuItem>Support</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Logout</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <main className="flex-1 flex flex-col p-4 gap-4 md:p-6 md:gap-0">
        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader className="pb-4">
              <CardTitle>Search Volume</CardTitle>
              <CardDescription>The estimated number of searches for this keyword per month.</CardDescription>
            </CardHeader>
            <CardContent className="flex items-center justify-center">
              <span className="text-4xl font-semibold">12.5K</span>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-4">
              <CardTitle>Clicks</CardTitle>
              <CardDescription>
                The number of clicks to your website from search results for this keyword.
              </CardDescription>
            </CardHeader>
            <CardContent className="flex items-center justify-center">
              <span className="text-4xl font-semibold">3.2K</span>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-4">
              <CardTitle>Organic Traffic</CardTitle>
              <CardDescription>
                The total number of visitors who found your website by clicking on a search engine's organic results.
              </CardDescription>
            </CardHeader>
            <CardContent className="flex items-center justify-center">
              <span className="text-4xl font-semibold">8.9K</span>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="pb-4">
              <CardTitle>Conversion Rate</CardTitle>
              <CardDescription>
                The percentage of visitors who complete a desired goal out of the total number of visitors.
              </CardDescription>
            </CardHeader>
            <CardContent className="flex items-center justify-center">
              <span className="text-4xl font-semibold">4.7%</span>
            </CardContent>
          </Card>
        </div>
        <Card className="flex-1">
          <CardHeader>
            <CardTitle>Textual Content</CardTitle>
            <CardDescription>The main text content for the SEO analysis.</CardDescription>
          </CardHeader>
          <CardContent className="prose max-w-none">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
              ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
              fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
              mollit anim id est laborum.
            </p>
          </CardContent>
        </Card>
        <div className="grid gap-4 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Related Keywords</CardTitle>
              <CardDescription>Keywords related to the content for SEO optimization.</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="grid gap-2 text-sm">
                <li>seo</li>
                <li>keywords</li>
                <li>content</li>
                <li>optimization</li>
                <li>search</li>
              </ul>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Targeted Keywords</CardTitle>
              <CardDescription>Keywords targeted for SEO optimization.</CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="grid gap-2 text-sm">
                <li>website</li>
                <li>traffic</li>
                <li>google</li>
                <li>ranking</li>
                <li>article</li>
              </ul>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>ID-TF Analysis</CardTitle>
              <CardDescription>Importance and term frequency of keywords in the text.</CardDescription>
            </CardHeader>
            <CardContent>
              <ol className="grid gap-2 text-sm list-decimal pl-4">
                <li>seo</li>
                <li>keywords</li>
                <li>content</li>
                <li>optimization</li>
                <li>search</li>
                <li>website</li>
                <li>traffic</li>
                <li>google</li>
                <li>ranking</li>
                <li>article</li>
              </ol>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Related Content Links</CardTitle>
              <CardDescription>Links to related articles or content for SEO improvement.</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableBody>
                  <TableRow>
                    <TableCell>
                      <Link className="underline" href="#">
                        How to Optimize Your Website for Search Engines
                      </Link>
                    </TableCell>
                    <TableCell className="text-sm">Tips for improving your website's SEO performance.</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Link className="underline" href="#">
                        The Importance of Keywords in Content Marketing
                      </Link>
                    </TableCell>
                    <TableCell className="text-sm">How keywords impact content visibility and engagement.</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>
                      <Link className="underline" href="#">
                        Best Practices for Writing SEO-Friendly Content
                      </Link>
                    </TableCell>
                    <TableCell className="text-sm">
                      Guidelines for creating content that ranks well in search results.
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
